app/__init__.py
from flask import Flask
from app.routes import main

def create_app():
    app = Flask(__name__)
    app.config['root'] = 'root'
    

    app.register_blueprint(main)

    return app

app/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, send_file
from app.scraper import extract_data
import pandas as pd
import os
import json
import io

main = Blueprint('main', __name__)

@main.route('/')
def home():
    return render_template('home.html')

@main.route('/results', methods=['POST'])
def results():
    # Récupérer les URLs soumises par l'utilisateur
    urls = request.form['urls']
    
    # Diviser les URLs par ligne et supprimer les espaces vides
    url_list = [url.strip() for url in urls.splitlines() if url.strip()]

    # Créer un DataFrame pour stocker les résultats
    all_data = []

    for url in url_list:
        data = extract_data(url)
        all_data.append(data)

    # Enregistrer les résultats dans un fichier CSV
    output_csv = 'data/extracted_info.csv'
    results_df = pd.DataFrame(all_data)
    if os.path.exists(output_csv):
        results_df.to_csv(output_csv, mode='a', header=False, index=False)
    else:
        results_df.to_csv(output_csv, mode='w', header=True, index=False)

    return render_template('results.html', data=all_data)

# Route to export data to CSV
@main.route('/export')
def export():
    file_path = os.path.join('data', 'extracted_info.csv')
    if os.path.exists(file_path):
        return send_file(file_path, mimetype='text/csv', as_attachment=True, download_name='extracted_info.csv')
    else:
        return "Le fichier CSV n'existe pas", 404

@main.route('/view_csv')
def view_csv():
    file_path = os.path.join('data', 'extracted_info.csv')

    if os.path.exists(file_path):
        df = pd.read_csv(file_path)
        data = df.to_dict(orient='records')
        
        # Paramètres de pagination
        page = request.args.get('page', 1, type=int)  # Page courante, par défaut 1
        per_page = 30  # Nombre de lignes par page
        total = len(data)  # Total des lignes
        
        # Calculer les données à afficher pour la page courante
        start = (page - 1) * per_page
        end = start + per_page
        paginated_data = data[start:end]

        # Calculer le nombre de pages
        total_pages = (total + per_page - 1) // per_page  # Arrondi vers le haut

        return render_template(
            'view.html',
            data=paginated_data,
            page=page,
            total_pages=total_pages
        )
    else:
        return "Le fichier CSV n'existe pas", 404

app/templates/home.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
        <meta name="generator" content="Hugo 0.122.0">
        <title>Scrapping google</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    </head>
    <body class="d-flex flex-column h-100">
        <!-- Begin page content -->
        <main class="flex-shrink-0">
            <div class="container">
                <h1 class="mt-5">Faire du scrapping google</h1>
                <p class="lead text-danger">Scrapping google peut bloquer votre IP.</p>
                <a href="{{ url_for('main.view_csv') }}">Voir résultat final</a>
                <form action="{{ url_for('main.results') }}" method="POST" class="mt-3">
                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Insérer votre url</label>
                        <textarea name="urls" rows="10" cols="50" placeholder="Entrez une URL par ligne..." class="form-control" required></textarea>
                    </div>
                    <button type="submit" class="btn btn-dark">Scraper</button>
                </form>
            </div>
        </main>
        <script src="/docs/5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    </body>
</html>

app/templates/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Résultats du Scraping</title>
    <!-- Lien Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .url-column {
            max-width: 200px; /* Limite la largeur à 200 pixels */
            overflow: hidden; /* Cache le texte qui dépasse */
            text-overflow: ellipsis; /* Ajoute des points de suspension (...) pour le texte qui déborde */
            white-space: nowrap; /* Empêche le texte de passer à la ligne suivante */
        }
    </style>
</head>
<body>
    <div class="container mt-5">
        <h1>Résultats du Scraping</h1>
        <a href="{{ url_for('main.export', data=data|tojson) }}" class="btn btn-success mt-3">Exporter en CSV</a>
        <a href="{{ url_for('main.home') }}" class="btn btn-primary mt-3">Retour</a>
        <!-- Tableau des résultats -->
        <table class="table table-bordered table-hover">
            <thead class="table-dark">
                <tr>
                    <th scope="col">Nom Google</th>
                    <th scope="col">Adresse</th>
                    <th scope="col">Numéro de téléphone</th>
                    <th scope="col" class="url-column">URL scrappée</th>
                    <th scope="col" class="url-column">URL du lien</th>
                    <th scope="col">Lundi</th>
                    <th scope="col">Mardi</th>
                    <th scope="col">Mercredi</th>
                    <th scope="col">Jeudi</th>
                    <th scope="col">Vendredi</th>
                    <th scope="col">Samedi</th>
                    <th scope="col">Dimanche</th>
                </tr>
            </thead>
            <tbody>
                {% if data %}
                    {% for entry in data %}
                        <tr>
                            <td>{{ entry['Nom Google'] }}</td>
                            <td>{{ entry['Adresse'] }}</td>
                            <td>{{ entry['Numéro de téléphone'] }}</td>
                            <td class="url-column"><a href="{{ entry['URL'] }}" target="_blank">{{ entry['URL'] }}</a></td>
                            <td class="url-column"><a href="{{ entry['URL du lien'] }}" target="_blank">{{ entry['URL du lien'] }}</a></td>
                            <td class="horaire">
                                {% set found = false %}
                                {% for horaire in entry['Horaires'] %}
                                    {% if horaire['Jour'] == 'lundi' %}
                                        {{ horaire['Horaires'] }}
                                        {% set found = true %}
                                    {% endif %}
                                {% endfor %}
                            </td>
                            <td class="horaire">
                                {% set found = false %}
                                {% for horaire in entry['Horaires'] %}
                                    {% if horaire['Jour'] == 'mardi' %}
                                        {{ horaire['Horaires'] }}
                                        {% set found = true %}
                                    {% endif %}
                                {% endfor %}
                            </td>
                            <td class="horaire">
                                {% set found = false %}
                                {% for horaire in entry['Horaires'] %}
                                    {% if horaire['Jour'] == 'mercredi' %}
                                        {{ horaire['Horaires'] }}
                                        {% set found = true %}
                                    {% endif %}
                                {% endfor %}
                            </td>
                            <td class="horaire">
                                {% set found = false %}
                                {% for horaire in entry['Horaires'] %}
                                    {% if horaire['Jour'] == 'jeudi' %}
                                        {{ horaire['Horaires'] }}
                                        {% set found = true %}
                                    {% endif %}
                                {% endfor %}
                            </td>
                            <td class="horaire">
                                {% set found = false %}
                                {% for horaire in entry['Horaires'] %}
                                    {% if horaire['Jour'] == 'vendredi' %}
                                        {{ horaire['Horaires'] }}
                                        {% set found = true %}
                                    {% endif %}
                                {% endfor %}
                            </td>
                            <td class="horaire">
                                {% set found = false %}
                                {% for horaire in entry['Horaires'] %}
                                    {% if horaire['Jour'] == 'samedi' %}
                                        {{ horaire['Horaires'] }}
                                        {% set found = true %}
                                    {% endif %}
                                {% endfor %}
                            </td>
                            <td class="horaire">
                                {% set found = false %}
                                {% for horaire in entry['Horaires'] %}
                                    {% if horaire['Jour'] == 'dimanche' %}
                                        {{ horaire['Horaires'] }}
                                        {% set found = true %}
                                    {% endif %}
                                {% endfor %}
                            </td>
                        </tr>
                    {% endfor %}
                {% else %}
                    <tr>
                        <td colspan="12">Aucune donnée trouvée.</td>
                    </tr>
                {% endif %}
            </tbody>
        </table>

        <a href="{{ url_for('main.home') }}" class="btn btn-primary mt-3">Retour</a>
    </div>

    <!-- Lien JavaScript Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

app/templates/view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Résultats</title>
    <!-- Lien Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .url-column {
            max-width: 200px; /* Limite la largeur à 200 pixels */
            overflow: hidden; /* Cache le texte qui dépasse */
            text-overflow: ellipsis; /* Ajoute des points de suspension (...) pour le texte qui déborde */
            white-space: nowrap; /* Empêche le texte de passer à la ligne suivante */
        }
    </style>
</head>
<body>
    <div class="container mt-5">
        <h1>Résultats du Scraping</h1>
        <a href="{{ url_for('main.export', data=data|tojson) }}" class="btn btn-success mt-3">Exporter en CSV</a>
        <a href="{{ url_for('main.home') }}" class="btn btn-primary mt-3">Retour</a>

        <!-- Tableau des résultats -->
        <table class="table table-bordered table-hover">
            <thead class="table-dark">
                <tr>
                    <th scope="col">Nom Google</th>
                    <th scope="col">Adresse</th>
                    <th scope="col">Numéro de téléphone</th>
                    <th scope="col" class="url-column">URL scrappée</th>
                    <th scope="col" class="url-column">URL du lien</th>
                    <th scope="col">Lundi</th>
                    <th scope="col">Mardi</th>
                    <th scope="col">Mercredi</th>
                    <th scope="col">Jeudi</th>
                    <th scope="col">Vendredi</th>
                    <th scope="col">Samedi</th>
                    <th scope="col">Dimanche</th>
                </tr>
            </thead>
            <tbody>
                {% if data %}
                    {% for entry in data %}
                        <tr>
                            <td>{{ entry['Nom Google'] }}</td>
                            <td>{{ entry['Adresse'] }}</td>
                            <td>{{ entry['Numéro de téléphone'] }}</td>
                            <td class="url-column"><a href="{{ entry['URL'] }}" target="_blank">{{ entry['URL'] }}</a></td>
                            <td class="url-column"><a href="{{ entry['URL du lien'] }}" target="_blank">{{ entry['URL du lien'] }}</a></td>
                            <td class="horaire">
                                {% for horaire in entry['Horaires'] if horaire['Jour'] == 'lundi' %}
                                    {{ horaire['Horaires'] }}
                                {% endfor %}
                            </td>
                            <td class="horaire">
                                {% for horaire in entry['Horaires'] if horaire['Jour'] == 'mardi' %}
                                    {{ horaire['Horaires'] }}
                                {% endfor %}
                            </td>
                            <td class="horaire">
                                {% for horaire in entry['Horaires'] if horaire['Jour'] == 'mercredi' %}
                                    {{ horaire['Horaires'] }}
                                {% endfor %}
                            </td>
                            <td class="horaire">
                                {% for horaire in entry['Horaires'] if horaire['Jour'] == 'jeudi' %}
                                    {{ horaire['Horaires'] }}
                                {% endfor %}
                            </td>
                            <td class="horaire">
                                {% for horaire in entry['Horaires'] if horaire['Jour'] == 'vendredi' %}
                                    {{ horaire['Horaires'] }}
                                {% endfor %}
                            </td>
                            <td class="horaire">
                                {% for horaire in entry['Horaires'] if horaire['Jour'] == 'samedi' %}
                                    {{ horaire['Horaires'] }}
                                {% endfor %}
                            </td>
                            <td class="horaire">
                                {% for horaire in entry['Horaires'] if horaire['Jour'] == 'dimanche' %}
                                    {{ horaire['Horaires'] }}
                                {% endfor %}
                            </td>
                        </tr>
                    {% endfor %}
                {% else %}
                    <tr>
                        <td colspan="12">Aucune donnée trouvée.</td>
                    </tr>
                {% endif %}
            </tbody>
        </table>

        <!-- Pagination -->
        <nav aria-label="Pagination">
            <ul class="pagination">
                <!-- Lien pour la page précédente -->
                {% if page > 1 %}
                    <li class="page-item">
                        <a class="page-link" href="{{ url_for('main.view_csv', page=page-1) }}">Précédent</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#">Précédent</a>
                    </li>
                {% endif %}

                <!-- Lien pour chaque page -->
                {% for p in range(1, total_pages + 1) %}
                    <li class="page-item {% if p == page %}active{% endif %}">
                        <a class="page-link" href="{{ url_for('main.view_csv', page=p) }}">{{ p }}</a>
                    </li>
                {% endfor %}

                <!-- Lien pour la page suivante -->
                {% if page < total_pages %}
                    <li class="page-item">
                        <a class="page-link" href="{{ url_for('main.view_csv', page=page+1) }}">Suivant</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#">Suivant</a>
                    </li>
                {% endif %}
            </ul>
        </nav>

        <a href="{{ url_for('main.home') }}" class="btn btn-primary mt-3">Retour</a>
    </div>

    <!-- Lien JavaScript Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>